# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a73efdf30fec92a3bd06d9ee099d7235b2e7fa46d59e10aca49b6d71534eb72d72fe81d00844323db29854b3994642cbe671130c416427cd7c7e08ff1383102b

test:
  secret_key_base: 7c303d2dc9b4f3a8c301b7bad94f69f3b8c10ba5806eb62dd501c540a703e605ea8a5fb1d942189020db2b15cfdcd0a9686417c746e3a5a1b237c4d54cc154dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
